"use client";

import React, { useState, useEffect } from "react"; // Added useEffect
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { InputFieldComponent } from "@/components/ui/InputField";
import AuthBanner from "@/components/auth/AuthBanner";
import AuthHeader from "@/components/auth/AuthHeader";
import { doctorRegister } from "@/app/services/doctor.api"; // Import doctorRegister service
import toast from "react-hot-toast"; // Import toast for notifications
import { Eye, EyeOff } from "lucide-react"; // Added icons for password toggle

// Define mode type
type RegisterMode = "user" | "doctor";

export default function DoctorRegisterPage() {
  const router = useRouter();
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    password: "",
    specialty: "",
  });
  const [agreedToTerms, setAgreedToTerms] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [mobileError, setMobileError] = useState("");
  const [showPassword, setShowPassword] = useState(false); // State for password visibility
  // --- NEW: Add state, initialize to 'doctor' ---
  const [registerMode, setRegisterMode] = useState<RegisterMode>("doctor");
  // --- END NEW ---

  // --- NEW: Effect to redirect if mode changes to user ---
  useEffect(() => {
    if (registerMode === "user") {
      router.push("/user/register");
      // Optional: Reset mode back if needed
      // setRegisterMode('doctor');
    }
  }, [registerMode, router]);
  // --- END NEW ---

  // Input handler remains the same
  const handleInputChange =
    (field: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
      const value = e.target.value;
      if (field === "phone") {
        if (!/^\d*$/.test(value)) return;
        setFormData((prev) => ({ ...prev, phone: value }));
        if (value.length === 0) setMobileError("");
        else if (value.length !== 10)
          setMobileError("Mobile must be 10 digits");
        else setMobileError("");
      } else {
        setFormData((prev) => ({ ...prev, [field]: value }));
      }
    };

  // --- Doctor Registration Submit Logic ---
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (registerMode !== "doctor") return;

    setIsLoading(true);

    if (mobileError || formData.phone.length !== 10) {
      toast.error("Enter a valid 10-digit mobile number");
      setIsLoading(false);
      return;
    }

    if (!agreedToTerms) {
      toast.error("You must agree to the terms");
      setIsLoading(false);
      return;
    }

    try {
      console.log("Registering Doctor:", formData);
      // Use the doctorRegister service instead of mock API
      // Create a doctor object without the id field (will be generated by API)
      const doctorData = {
        firstName: formData.firstName,
        lastName: formData.lastName,
        email: formData.email,
        phone: formData.phone,
        password: formData.password,
        specialty: formData.specialty,
        isAvailable: true,
      };

      const result = await doctorRegister(doctorData);
      console.log("Registration result:", result);

      if (!result.success) {
        toast.error(result.error || "Registration failed");
        throw new Error(result.message || "Registration failed");
      }

      const newDoctor = result.data;

      // Show success toast instead of alert
      toast.success("Doctor Registration Successful! Please login to continue");

      router.push("/doctor/login");
    } catch (error) {
      console.error(error);
      toast.error("Registration failed");
    } finally {
      setIsLoading(false);
    }
  };
  // --- End Submit Logic ---

  const handleLoginRedirect = () => router.push("/doctor/login"); // Link back to doctor login

  return (
    <div className="min-h-screen flex flex-col bg-white overflow-hidden">
      {/* HEADER - Pass userType="doctor" */}
      <AuthHeader activeLink="register" userType="doctor" />

      {/* MAIN CONTENT */}
      <div className="flex flex-col md:flex-row flex-1">
        {/* LEFT SIDE BANNER */}
        <AuthBanner />

        {/* RIGHT SIDE FORM */}
        <div className="flex-1 flex flex-col justify-center items-center px-8 py-12">
          {/* --- NEW: User/Doctor Toggle Buttons --- */}
          <div className="flex justify-center space-x-2 border border-gray-200 rounded-lg p-1 mb-8 w-full max-w-sm">
            <button
              onClick={() => setRegisterMode("user")} // Will trigger redirect via useEffect
              className={`flex-1 py-2 px-4 rounded-md text-sm font-medium transition-colors ${
                registerMode === "user"
                  ? "bg-cyan-500 text-white shadow-sm"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              User
            </button>
            <button
              onClick={() => setRegisterMode("doctor")}
              className={`flex-1 py-2 px-4 rounded-md text-sm font-medium transition-colors ${
                registerMode === "doctor"
                  ? "bg-cyan-500 text-white shadow-sm"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              Doctor
            </button>
          </div>
          {/* --- END NEW: Toggle Buttons --- */}

          {/* Only show the doctor form if mode is 'doctor' */}
          {registerMode === "doctor" && (
            <>
              <h2 className="text-2xl font-semibold text-gray-800 mb-6 text-center">
                Create Account
              </h2>
              <form
                onSubmit={handleSubmit}
                className="space-y-4 w-full max-w-md"
              >
                {/* First Name */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    First Name
                  </label>
                  <InputFieldComponent
                    type="text"
                    placeholder="Enter first name"
                    value={formData.firstName}
                    required
                    onChange={handleInputChange("firstName")}
                  />
                </div>
                {/* Last Name */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Last Name
                  </label>
                  <InputFieldComponent
                    type="text"
                    placeholder="Enter Last name"
                    value={formData.lastName}
                    required
                    onChange={handleInputChange("lastName")}
                  />
                </div>
                {/* Email */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Email
                  </label>
                  <InputFieldComponent
                    type="email"
                    placeholder="Enter email address"
                    value={formData.email}
                    required
                    onChange={handleInputChange("email")}
                  />
                </div>
                {/* Mobile Number */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Mobile Number
                  </label>
                  <InputFieldComponent
                    type="tel"
                    placeholder="Enter 10-digit mobile"
                    value={formData.phone}
                    required
                    onChange={handleInputChange("phone")}
                    maxLength={10}
                  />
                  {mobileError && (
                    <p className="text-red-500 text-xs mt-1">{mobileError}</p>
                  )}
                </div>
                {/* Password */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Password
                  </label>
                  <div className="relative">
                    <InputFieldComponent
                      type={showPassword ? "text" : "password"}
                      placeholder="Create a password"
                      value={formData.password}
                      required
                      onChange={handleInputChange("password")}
                    />
                    <button
                      type="button"
                      className="absolute inset-y-0 right-0 pr-3 flex items-center"
                      onClick={() => setShowPassword(!showPassword)}
                    >
                      {showPassword ? (
                        <EyeOff className="h-5 w-5 text-gray-500" />
                      ) : (
                        <Eye className="h-5 w-5 text-gray-500" />
                      )}
                    </button>
                  </div>
                </div>
                {/* Specialization */}
                <div>
                  <label className="block text-sm font-medium mb-1">
                    Specialization
                  </label>
                  <InputFieldComponent
                    type="text"
                    placeholder="e.g., Cardiologist"
                    value={formData.specialty}
                    required
                    onChange={handleInputChange("specialty")}
                  />
                </div>
                {/* Terms & Conditions */}
                <div className="flex items-center gap-2 pt-2">
                  <input
                    type="checkbox"
                    id="terms"
                    checked={agreedToTerms}
                    onChange={(e) => setAgreedToTerms(e.target.checked)}
                    className="w-4 h-4 accent-cyan-400"
                  />
                  <label htmlFor="terms" className="text-sm text-gray-600">
                    I agree to the{" "}
                    <a href="#" className="text-pink-500 hover:underline">
                      {" "}
                      Terms & Conditions{" "}
                    </a>
                  </label>
                </div>
                {/* Register Button */}
                <Button
                  type="submit"
                  disabled={!agreedToTerms || isLoading || !!mobileError}
                  className="w-full py-3 mt-4 bg-cyan-500 hover:bg-cyan-600 text-white font-semibold rounded-xl transition-colors duration-200"
                >
                  {isLoading ? "Creating Account..." : "Register as Doctor"}
                </Button>
              </form>

              {/* Link to Login */}
              <p className="text-center text-sm text-gray-600 mt-6">
                Already have an account?{" "}
                <button
                  onClick={handleLoginRedirect}
                  className="font-medium text-cyan-600 hover:underline"
                >
                  Login Here
                </button>
              </p>
            </>
          )}
          {/* Placeholder if mode is user before redirect */}
          {registerMode === "user" && (
            <p className="text-gray-500">Redirecting to user registration...</p>
          )}
        </div>
      </div>
    </div>
  );
}
