"use client";

import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Calendar, Clock, User } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { InputFieldComponent } from "@/components/ui/InputField";
import mockData from "@/lib/mockData.json"; // To get doctor info
import { Doctor } from "@/lib/types/doctor";
import Image from "next/image";
import Link from "next/link";
import {
  createAppointment,
  isTimeSlotBooked,
} from "@/app/services/appointments.api";
import { Appointment } from "@/lib/types/appointment";
import { createNotification } from "@/app/services/notifications.api";

// Type for the User (from localStorage)
type UserInfo = {
  id: string;
  name: string;
  email: string;
  phone: string;
  [key: string]: any; // Allow other properties
};

export default function BookAppointmentPage() {
  const router = useRouter();
  const params = useParams();
  const doctorId = params?.doctorId as string;

  const [doctor, setDoctor] = useState<Doctor | null>(null);
  const [user, setUser] = useState<UserInfo | null>(null);
  const [formData, setFormData] = useState({
    date: "",
    time: "",
    problem: "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Get Doctor and User info on load
  useEffect(() => {
    if (doctorId) {
      // Find the doctor from mock data
      const foundDoctor = mockData.doctors.find(
        (d: Doctor) => d.id === doctorId
      );
      if (foundDoctor) {
        setDoctor(foundDoctor);
      } else {
        setError("Doctor not found.");
      }
    }

    // Get user data from localStorage
    const userString = localStorage.getItem("user");
    if (userString) {
      try {
        setUser(JSON.parse(userString));
      } catch (e) {
        console.error("Failed to parse user data", e);
        setError("You must be logged in to book.");
      }
    } else {
      setError("You must be logged in to book.");
    }
  }, [doctorId]);

  const handleInputChange =
    (field: string) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setFormData((prev) => ({ ...prev, [field]: e.target.value }));
    };

  // --- Handle Booking Submission ---
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (
      !doctor ||
      !user ||
      !formData.date ||
      !formData.time ||
      !formData.problem
    ) {
      setError("Please fill out all fields.");
      return;
    }
    setIsSubmitting(true);
    setError(null);

    try {
      // Check if time slot is already booked
      const slotBooked = await isTimeSlotBooked(
        doctor.id,
        formData.date,
        formData.time
      );

      if (slotBooked) {
        setError(
          "This time slot is already booked. Please choose another time."
        );
        setIsSubmitting(false);
        return;
      }

      // Get day name from date
      const dayName = new Date(formData.date).toLocaleDateString("en-US", {
        weekday: "long",
      });

      // Prepare appointment data
      const appointmentData: Appointment = {
        id: "", // Will be generated by the API
        tokenNo: "", // Will be generated by the API
        patientId: user.id,
        doctorId: doctor.id,

        doctor: {
          firstName: doctor.firstName,
          lastName: doctor.lastName,
          specialty: doctor.specialty,
          qualifications: doctor.qualifications,
          image: doctor.image || "/male-doctor.png",
        },

        date: formData.date,
        time: formData.time,
        timeSlot: formData.time,
        day: dayName,

        type: "In-person",
        status: "Upcoming",
        paymentStatus: "Not paid",

        patientDetails: {
          fullName: user.name,
          age: user.age || 30, // Use user age if available, otherwise placeholder
          gender: user.gender || "Other",
          phone: user.phone,
          relationship: "Self",
          problem: formData.problem,
        },
      };

      // Call the createAppointment function
      const result = await createAppointment(appointmentData);

      if (result) {
        // Success! Navigate to the appointment review page
        await createNotification({
          recipientId: appointmentData.doctorId,
          recipientRole: "doctor",
          title: "New Appointment",
          message: `You have a new appointment with ${appointmentData.patientDetails?.fullName || 'Patient'}`,
          type: "appointment",
          targetUrl: `/doctors/appointment`,
          relatedId: appointmentData.id,
          createdAt: new Date().toISOString(),
          read: false,
        });
        router.push(`/user/appointment/${result.id}/review`);
      } else {
        setError("Failed to create appointment. Please try again.");
      }
    } catch (err: any) {
      console.error(err);
      setError(
        err.message || "An error occurred while booking the appointment."
      );
    } finally {
      setIsSubmitting(false);
    }
  };
  // --- End Submit ---

  if (!doctor || !user) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <div className="text-center">
          <p className="text-lg text-red-600">{error || "Loading..."}</p>
          <Link href="/user/dashboard">
            <span className="text-cyan-600 hover:underline mt-4 inline-block">
              Go to Dashboard
            </span>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm sticky top-0 z-10">
        <div className="max-w-3xl mx-auto p-4 flex items-center gap-3">
          <button
            onClick={() => router.back()}
            className="p-2 text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft size={20} />
          </button>
          <h1 className="text-lg font-semibold text-gray-800">
            Book Appointment
          </h1>
        </div>
      </header>

      {/* Form */}
      <main className="max-w-3xl mx-auto p-4 sm:p-6">
        <div className="bg-white p-6 rounded-lg shadow-md">
          {/* Doctor Info */}
          <div className="flex items-center gap-4 mb-6 pb-4 border-b border-gray-200">
            <Image
              src={doctor.image || "/male-doctor.png"}
              alt={`${doctor.firstName} ${doctor.lastName}`}
              width={64}
              height={64}
              className="rounded-full w-16 h-16 object-cover"
            />
            <div>
              <h2 className="text-xl font-semibold">{`${doctor.firstName} ${doctor.lastName}`}</h2>
              <p className="text-cyan-600">{doctor.specialty}</p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Date Input */}
            <div>
              <label
                htmlFor="date"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Date
              </label>
              <InputFieldComponent
                id="date"
                type="date"
                value={formData.date}
                onChange={handleInputChange("date")}
                min={new Date().toISOString().split("T")[0]}
                required
              />
            </div>

            {/* Time Input */}
            <div>
              <label
                htmlFor="time"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Time
              </label>
              <InputFieldComponent
                id="time"
                type="time"
                value={formData.time}
                onChange={handleInputChange("time")}
                required
              />
            </div>

            {/* Reason Input */}
            <div>
              <label
                htmlFor="problem"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Reason for Visit
              </label>
              <textarea
                id="problem"
                value={formData.problem}
                onChange={handleInputChange("problem")}
                required
                rows={3}
                className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-cyan-400 transition"
                placeholder="Briefly describe your health problem"
              />
            </div>

            {/* Error Display */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-3">
                <p className="text-red-600 text-sm">{error}</p>
              </div>
            )}

            {/* Submit Button */}
            <div className="pt-4">
              <Button
                type="submit"
                disabled={isSubmitting}
                className="w-full bg-cyan-500 hover:bg-cyan-600 text-white font-semibold rounded-lg transition-colors duration-200 px-6 py-3 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isSubmitting ? "Booking..." : "Confirm Appointment"}
              </Button>
            </div>
          </form>
        </div>
      </main>
    </div>
  );
}
